### ISSUE TITLE
手机使用菜单栏切换上方状态栏会遮住分类名称！

### ISSUE THREAD

**Issue by 2293310198** [geekape/geek-navigation#16]
手机使用菜单栏切换上方状态栏会遮住分类名称。

<div class="box">
--
  | <a href="#" name="sill"></a>
  | <div class="sub-category">
  | <div><i class="iconfont icon-blogger"></i>技术博客</div>
  | </div>
  | <div>

**Comment by geekape** [comment]
如果是点击分类的时候，锚点跳转到指点块，名称被挡住的问题，新版本已经修复了
