### ISSUE TITLE
请问作者方便能写一个面向小白用户的readme吗

### ISSUE THREAD

**Issue by toyqiu** [geekape/geek-navigation#17]
一直用的静态版，添加的时候改改html，有一天量太大了，于是想折腾折腾vue2版。

群晖用户，http后端服务器Apache HTTP Server2.2，php 7.0
下载了mongoDB，不晓得【数据库的名字】要怎么配置（官方文档只给了数据库用户名密码的环境写法）

一直无法成功启动

**Comment by geekape** [comment]
> 一直用的静态版，添加的时候改改HTML，有一天量太大了，于是想折腾折腾vue2版。
> 
> 群晖用户，http后端服务器Apache HTTP Server2.2，php 7.0 
> 下载了mongoDB，不晓得【数据库的名字】要怎么配置（官方文档只给了数据库用户名密码的环境写法）
> 
> 一直无法成功启动

线上mongodb连接的上吗，下个mongodb gui工具看看

![image](https://user-images.githubusercontent.com/27131698/57222985-281cd080-7037-11e9-8f38-cc58e591ec29.png)
