### ISSUE TITLE
按照redeme部署后，首页不能访问

### ISSUE THREAD

**Issue by ucfyao** [geekape/geek-navigation#18]
启动后，默认域名为 http://localhost:8080/
api域名为 http://localhost:3000/api/index/

在本地会不能链接，默认API接口请求的端口是 http://localhost:8080/

另外会有 mongo 的默认数据吗？本地部署我看链接是远程，用户系统会有问题

**Comment by geekape** [comment]
你把数据库的连接地址远程的删掉，换成本地的//localhost:27017。（前端是确保你本地mongodb已经部署好了，并且已启动）。

默认api是localhost:3000，［不能访问］是页面不能打开还是没数据？

**Comment by ucfyao** [comment]
1.无数据问题
![image](https://user-images.githubusercontent.com/11612671/57753956-f931e900-771f-11e9-8c27-78bffff768af.png)
按照redeme执行完毕后报错,将vue.config 中的 4000改为3000可以解决这个问题，但是接口有返回了，页面依然没有显示。
![image](https://user-images.githubusercontent.com/11612671/57754138-575ecc00-7720-11e9-9977-ce23785c8463.png)

**Comment by ucfyao** [comment]
2.mongo 的默认数据问题
我看了下，后台可以直接进入。现在没有用户系统，暂时无需默认数据填充。

**Comment by ucfyao** [comment]
这个问题我也解决了。
要加一行
<div v-if="sub"> 
才会显示。

**Comment by geekape** [comment]
我看了一下数据库有问题，导致数据渲染报错

**Comment by ucfyao** [comment]
添加和删除也有问题。数据不同步。。这问题也太多了

**Comment by geekape** [comment]
谢谢反馈，你提交的问题已经修复
