### ISSUE TITLE
本地安装报错 

### ISSUE THREAD

**Issue by hustboylle** [geekape/geek-navigation#19]
Build failed with error code: 1
npm ERR! Windows_NT 10.0.17763
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\geek-navigation-vue2\geek-navigation-vue2\npm-debug.log

**Comment by geekape** [comment]
安装包时候出错，请确定你是否正确使用npm，推荐使用cnpm

**Comment by geekape** [comment]
> Build failed with error code: 1
> npm ERR! Windows_NT 10.0.17763
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "i"
> npm ERR! node v4.4.3
> npm ERR! npm v2.15.1
> npm ERR! code ELIFECYCLE
> 
> npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the node-sass@4.12.0 postinstall script 'node scripts/build.js'.
> npm ERR! This is most likely a problem with the node-sass package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR! node scripts/build.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR! npm bugs node-sass
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!
> npm ERR! npm owner ls node-sass
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR! D:\geek-navigation-vue2\geek-navigation-vue2\npm-debug.log
安装包时候出错，请确定你是否正确使用npm，推荐使用cnpm
