### ISSUE TITLE
大神，可以在网页顶部加一个搜索引擎吗？然后可以选择搜索引擎的那种，这样就很完美了。

### ISSUE THREAD

**Issue by Liby94** [geekape/geek-navigation#2]

**Comment by hitkoo** [comment]
是啊，加个百度和谷歌的搜索引擎在顶部，浮动的那种，可以切换。在手机就不会显示百度的垃圾文章了。希望大神能添加一下

**Comment by Liby94** [comment]
我不会写js代码，只是仿着代码内容改了下，你也可以试着改一下自定义你的首页。
https://htmlpreview.github.io/?https://github.com/Liby94/navigationHtml/blob/master/index.html
