### ISSUE TITLE
编译出来跑不起来！

### ISSUE THREAD

**Issue by 670292062** [geekape/geek-navigation#21]
首先执行git clone https://github.com/geekape/geek-navigation/tree/json-navigation提示not found
我直接下载的zip，cnpm install，然后run，可以运行
然后npm run build编译出来，就挂了，打开有背景，但没有内容。大佬能提供一份直接编译的不？
还是我命令不对？
小白用户，见谅！

**Comment by geekape** [comment]
将我新上传的dist目录下的所有文件放在域名根目录下访问即可

**Comment by geekape** [comment]
> 首先执行git clone [https://github.com/geekape/geek-navigation/tree/json-navigation提示not](https://github.com/geekape/geek-navigation/tree/json-navigation%E6%8F%90%E7%A4%BAnot) found
> 我直接下载的zip，cnpm install，然后run，可以运行
> 然后npm run build编译出来，就挂了，打开有背景，但没有内容。大佬能提供一份直接编译的不？
> 还是我命令不对？
> 小白用户，见谅！

将我新上传的dist目录下的所有文件放在域名根目录下访问即可

**Comment by 670292062** [comment]
> 
> 
> > 首先执行git clone [https://github.com/geekape/geek-navigation/tree/json-navigation提示not](https://github.com/geekape/geek-navigation/tree/json-navigation%E6%8F%90%E7%A4%BAnot) found
> > 我直接下载的zip，cnpm install，然后run，可以运行
> > 然后npm run build编译出来，就挂了，打开有背景，但没有内容。大佬能提供一份直接编译的不？
> > 还是我命令不对？
> > 小白用户，见谅！
> 
> 将我新上传的dist目录下的所有文件放在域名根目录下访问即可

谢谢，大佬，我已经搞定了，原因是源码路由里面URL里没有带#。我自己没有服务器，我把项目弄到码云上的，码云的pagas，不许用根目录，必须指定index.html。如果把#屏蔽掉，貌似不能直接用打开文件的方式访问，故出现上述情况。最后谢谢大佬无私奉献！
