### ISSUE TITLE
跪求怎么用FTP的方法安装上传，谢谢

### ISSUE THREAD

**Issue by dreamchonghua** [geekape/geek-navigation#22]
跪求怎么用FTP的方法安装上传，谢谢

**Comment by geekape** [comment]
> 跪求怎么用FTP的方法安装上传，谢谢

将我新上传的dist目录下的所有文件放在域名根目录下访问即可

**Comment by 670292062** [comment]
> 
> 
> 跪求怎么用FTP的方法安装上传，谢谢

你成功了吗？
