### ISSUE TITLE
不适合在NAS上安装么？完全小白，但真的喜欢这个页面设计风格。

### ISSUE THREAD

**Issue by fiohappy** [geekape/geek-navigation#26]

**Comment by geekape** [comment]
不太懂NAS是什么，-_-

**Comment by fiohappy** [comment]
还以为不会收到回复，没想到你是个认真的人。先说声谢谢。NAS的话，你可以搜一下，个人家用的云存储服务器。有品牌的：群晖、铁威马、QNAP、等等。。。也可以自己做FREENAS，或者非官方的黑群晖。。。另外我这三脚猫的一点点了解，百度了一下，应该可以在NAS上实现这个导航页部署。NAS里面有docker可以安装mongodb,只是剩下怎么把数据库和页面对接上，对我来说就完全是天书了。。。

**Comment by geekape** [comment]
部署什么的我是直接安装的宝塔，一键安装mongodb和各种东西，https://www.bt.cn/

**Comment by pmpfun** [comment]
> 部署什么的我是直接安装的宝塔，一键安装mongodb和各种东西，[https：](https://www.bt.cn/) //www.bt.cn/[](https://www.bt.cn/)

宝塔中，是用pm2搭建，还是安装mongodb搭建，指导下
