### ISSUE TITLE
添加网站处 下拉菜单与自定义应该可以互相切换 以及下拉菜单可以做成多级菜单那种样式

### ISSUE THREAD

**Issue by 2015WUJI01** [geekape/geek-navigation#28]
1. 点击自定义分类后，需要刷新才能回到原来下拉菜单的状态，这好像不太方便。如果用户输入了信息，但是不小心触发自定义分类，应该有切换按钮可以返回下拉菜单，以保留用户原来的输入。

2. 目前的分类项有点多了好像，一次全部展示出来要找很久。所以最好的话可以做成二级菜单那种样式

**Comment by geekape** [comment]
已加入待办
