### ISSUE TITLE
想把vue2安装在阿里云虚拟主机上的几个小问题。

### ISSUE THREAD

**Issue by fiohappy** [geekape/geek-navigation#34]
vue2版的环境是啥配置？
WordPress的环境可以兼容么？
我是完全不懂编程的菜鸟，可以在说明文件里介绍的更详细些么？
json版编辑页面上的站点，用啥程序合适呢？

非常感谢分享，盼回复。

**Comment by geekape** [comment]
可以下载个宝塔，一键安装nodejs和pm，mongodb等工具
