### ISSUE TITLE
关于静态导航（JSON文件）版本，如何放在非网站根目录下用

### ISSUE THREAD

**Issue by thos001** [geekape/geek-navigation#35]
不想放在网站根目录下用，想放在子目录下用，例http://127.0.0.1:5000/static/weblink/index.html
但是点开一片空白，对前端不多了解，请问js做了什么限制，需要修改哪一段js代码才能在非根目录下用

**Comment by geekape** [comment]
这跟你服务器配置的有问题，你可以安装个宝塔，可以很方便的修改网站根目录

**Comment by thos001** [comment]
只打算本机电脑用，只用dist这个文件夹下的文件，不想部署到根目录而是放到python的flask框架下的静态文件夹下用，类似http://127.0.0.1:5000/static/dist/index.html这种路径访问，不行吗？需要修改原项目的路径配置重新编译才能吗？
