### ISSUE TITLE
npm run serve时错误，我尝试百度解决，但是未能解决该问题

### ISSUE THREAD

**Issue by ymyguang** [geekape/geek-navigation#42]
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! path /root/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/root/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by geekape** [comment]
npm包安装了吗？npm i

**Comment by 1668558792** [comment]
我在Debian10的系统环境下安运行了：apt-get install npm，并且显示安装成功。
刚才执行了，npm i得到了如下信息：
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.


希望您能有时间可以指点一些这个问题，万分感谢！

**Comment by 1668558792** [comment]
并且在执行npm install时，也遇到了一些警告，信息如下
root@debian:~# npm install
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

**Comment by 1668558792** [comment]
您好，首先感谢你能回复我的问题，当我看到这个项目时很兴奋，很想尝试这个项目，但是当我按照你的步骤执行时，遇到了一些错误，问题正如在Github上所说的那样（尝试解决，但是没有成功）
我在Debian10的系统环境下安运行了：apt-get install npm，并且显示安装成功。刚才执行了，npm i得到了如下信息：
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.





希望您能有时间可以指点一些这个问题，万分感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "geekape"<notifications@github.com&gt;; 
发送时间: 2020年1月11日(星期六) 晚上10:23
收件人: "geekape/geek-navigation"<geek-navigation@noreply.github.com&gt;; 
抄送: "2096304869"<2096304869@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [geekape/geek-navigation] npm run serve时错误，我尝试百度解决，但是未能解决该问题 (#42)




npm包安装了吗？npm i

**Comment by geekape** [comment]
已更新图片教程，有兴趣可以再试试
