### ISSUE TITLE
nginx配置报错

### ISSUE THREAD

**Issue by zsbai** [geekape/geek-navigation#49]
location /api {
  proxy_pass http://176.122.147.140:3000/api;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection 'upgrade';
  proxy_set_header Host $host;
  proxy_cache_bypass $http_upgrade;
}
location / {
  try_files $uri $uri/ /index.html;
}
报错
nginx: [emerg] "location" directive is not allowed here in /www/server/nginx/conf/nginx.conf:91
nginx: configuration file /www/server/nginx/conf/nginx.conf test failed

**Comment by geekape** [comment]
你没放进server里面吗
![image](https://user-images.githubusercontent.com/27131698/90631586-98179000-e255-11ea-99a3-03671afd9e9d.png)

**Comment by zsbai** [comment]
哦哦原来是放进站点的配置文件...请问这个的作用是什么啊？

**Comment by zsbai** [comment]
> 你没放进server里面吗
> ![image](https://user-images.githubusercontent.com/27131698/90631586-98179000-e255-11ea-99a3-03671afd9e9d.png)

谢谢，可以添加了...我之前没有加到站点的配置文件里，可是添加后还是无法通过域名访问啊？

**Comment by geekape** [comment]
域名解析了吗？端口开放了吗？

**Comment by zsbai** [comment]
> 域名解析了吗？端口开放了吗？

都弄好了，域名访问出现nginx默认的页面...用ip+8080访问就没问题

**Comment by zsbai** [comment]
> 域名解析了吗？端口开放了吗？

配置反向代理后域名访问Invalid Host header，ip访问就没问题...

**Comment by geekape** [comment]
已更新图片教程
