### ISSUE TITLE
在火狐中，左边的列表有滚动条！

### ISSUE THREAD

**Issue by 670292062** [geekape/geek-navigation#5]
样式太丑了，我把它可耻的隐藏了。大神能改改源码否？

**Comment by oicu** [comment]
ie里一样的。我也隐藏了。

style.css隐藏滚动条
.left-bar .nav-item{min-height:100vh;overflow-y:scroll}
改为
.left-bar .nav-item{min-height:100vh;overflow:hidden}

index.html里注释
<i class="line"></i>
