### ISSUE TITLE
大佬，部署nuxt版本时候报错！！！麻烦看一下。。。

### ISSUE THREAD

**Issue by hengeek** [geekape/geek-navigation#55]
大佬，部署nuxt版本时候报错！！！麻烦看一下。。。
![](http://img.hengeek.cn/20201214180455.png)

**Comment by hengeek** [comment]
[http://img.hengeek.cn/20201214180455.png](url)

**Comment by hengeek** [comment]
![Uploading 20201214180455.png…]()

**Comment by hengeek** [comment]
[http://img.hengeek.cn/20201214180455.png](url)

**Comment by 2926295173** [comment]
第一个报错，需要添加个属性，就行，建议百度 @hengeek
